### ISSUE TITLE
图片文件类型错误

### ISSUE THREAD

**Issue by seqilove** [beizhedenglong/ins-viewer#3]
图片下载后在相册里查看不了，用文件查看器查看后发现在DCIM文件夹里存在，没有文件类型后缀，希望能修复下这个BUG 谢谢。
手机是 小米NOTE3     Android8.1

**Comment by beizhedenglong** [comment]
修了，https://github.com/beizhedenglong/ins-viewer/commit/92f07e7a330c173818d7215746b0edb3b0d75bcf，手边没有安卓手机，你试下
